[env:esp32s3cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7
    256dpi/MQTT@^2.5
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
